version: 1.0.{build}

# TODO: Support Visual Studio 2017
image: Visual Studio 2019

platform: x64

environment:
  matrix:
    - BUILD_SHARED: OFF
      COMPILER: msvc2019

for:
  - matrix:
      only:
        - OQS_USE_OPENSSL: OFF
    before_build:
      - cmd: |-
             choco install openssl
             choco install -y strawberryperl
             SET "OPENSSL_ROOT_DIR=C:\OpenSSL-Win64"

before_build:
    - ps: >-
        Install-Module VSSetup -Scope CurrentUser
    - ps: >-
        Get-VSSetupInstance -All
    - ps: >-
        gci env:* | sort-object name
    - ps: >-
        If ($env:Platform -Match "x86") {
            $env:VCVARS_PLATFORM="x86"
            $env:TARGET="VC-WIN32 no-asm --strict-warnings"
        } Else {
            $env:VCVARS_PLATFORM="amd64"
            $env:TARGET="VC-WIN64A-masm"
        }
    - ps: >-
        If ($env:Configuration -Match "shared") {
            $env:SHARED="no-makedepend"
        } ElseIf ($env:Configuration -Match "minimal") {
            $env:SHARED="no-shared no-dso no-makedepend no-aria no-async no-autoload-config no-blake2 no-bf no-camellia no-cast no-chacha no-cmac no-cms no-comp no-ct no-des no-dgram no-dh no-dsa no-dtls no-ec2m no-engine no-filenames no-gost no-idea no-mdc2 no-md4 no-multiblock no-nextprotoneg no-ocsp no-ocb no-poly1305 no-psk no-rc2 no-rc4 no-rmd160 no-seed no-siphash no-sm2 no-sm3 no-sm4 no-srp no-srtp no-ssl3 no-ssl3-method no-ts no-ui-console no-whirlpool no-asm -DOPENSSL_SMALL_FOOTPRINT"
        } Else {
            $env:SHARED="no-shared no-makedepend"
        }
    - ps: >-
        if (-not $env:APPVEYOR_PULL_REQUEST_NUMBER`
            -or (&git log -1 $env:APPVEYOR_PULL_REQUEST_HEAD_COMMIT |
                 Select-String "\[extended tests\]") ) {
            $env:EXTENDED_TESTS="yes"
        }

build_script:
  - cmd: '%APPVEYOR_BUILD_FOLDER%\appveyor_build.bat'

before_test:
  - cmd: |-
         SET "PATH=C:\Python37;C:\Python37\Scripts;%PATH%"
         pip.exe install pytest pytest-xdist psutil

test_script:
  - cmd: |-
         cd %APPVEYOR_BUILD_FOLDER%
         set PATH=%cd%;%PATH% && if not exist tmp (mkdir tmp) && python -m pytest --numprocesses=auto --verbose  oqs-test/test_tls_basic.py oqs-test/test_cms.py --junitxml=test-results.xml

artifacts:
  - path: test-results.xml
    name: test logs
    type: File

after_test:
  - ps: |-
        $wc = New-Object 'System.Net.WebClient'
        $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-results.xml))
